slam_toolbox:
  ros__parameters:
    use_sim_time: true

    slam_toolbox: online_async
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    scan_topic: /scan

    # Çoğu parametre varsayılanda bırakıldı; temel mapping için yeterli
    resolution: 0.05
    max_laser_range: 30.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    mode: mapping

